### ISSUE TITLE
Stuck on 100% loading when creating new world, crash-report gets created

### ISSUE THREAD

**Issue by SeriousCreeper** [Harvest-Festival/Shopaholic#1]
Added mostly your new mods + a few others, and once i go to create a new world, it loads till 100%, then gets stuck and creates a crash report (it doesn't actually crash, but it won't continue loading). 

Crash report! https://pastebin.com/36Na6yub

**Comment by joshiejack** [comment]
Fixed in penguin lib 0.4.1
