### ISSUE TITLE
Failed to load example datapack - "Simple Shops"

### ISSUE THREAD

**Issue by mortuusars** [Harvest-Festival/Shopaholic#2]
Happens when using /reload, or starting a world.

Error in log file.
https://pastebin.com/raw/NyMfuT4m

Forge 36.1.62.

**Comment by joshiejack** [comment]
I did change something at some point between release. I can't remember if I updated the datapack, thought I did or maybe just another issue. I'll have to test it/check when I'm home tomorrow. Either way i shouldn't let the game crash if a user error is made.

**Comment by joshiejack** [comment]
Okay I just looked at my files. Edit the shops.csv

Change background texture field to default and vendor id to villager

I must have messed up the data generation and got them mixed up

(it was crashing because it couldn't find the vendor but yeah it should log NOT crash)

**Comment by mortuusars** [comment]
Yes, it fixed it. It was not crashing the client. Just not loading datapack.

**Comment by joshiejack** [comment]
Ahh ok. Good to know.

**Comment by joshiejack** [comment]
Updated the example file now >.>
